# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x02sd\"\x1a\n\nFloatArray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"@\n\rVerifyRequest\x12\x0f\n\x07x_draft\x18\x01 \x03(\x05\x12\x0f\n\x07q_value\x18\x02 \x03(\x02\x12\r\n\x05gamma\x18\x03 \x01(\x05\"|\n\x0eVerifyResponse\x12\t\n\x01j\x18\x01 \x01(\x05\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x05\x12\n\n\x02pj\x18\x03 \x03(\x02\x12\n\n\x02xj\x18\x04 \x03(\x05\x12\x10\n\x08llm_time\x18\x05 \x01(\x02\x12\x13\n\x0b\x63orrect_num\x18\x06 \x01(\x05\x12\x12\n\nreject_num\x18\x07 \x01(\x05\x32;\n\x08SDVerify\x12/\n\x06Verify\x12\x11.sd.VerifyRequest\x1a\x12.sd.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATARRAY']._serialized_start=18
  _globals['_FLOATARRAY']._serialized_end=44
  _globals['_VERIFYREQUEST']._serialized_start=46
  _globals['_VERIFYREQUEST']._serialized_end=110
  _globals['_VERIFYRESPONSE']._serialized_start=112
  _globals['_VERIFYRESPONSE']._serialized_end=236
  _globals['_SDVERIFY']._serialized_start=238
  _globals['_SDVERIFY']._serialized_end=297
# @@protoc_insertion_point(module_scope)
